### DISCUSSION TITLE
Trying Keygen for the first time (Docker compose structure)

### DISCUSSION THREAD

**Discussion by joanesinurrietasmartpm** [keygen-sh/community#126] [Q&A] [answered]
Hello,

in my company we are looking for a licensing tool for our app. I wanted to try Keygen CE locally to test it's capabilities. I created this docker compose following the documentation:

```
version: '3.5'

services:
  mic-keygen:
    container_name: keygen
    image: keygen/api:v1.2
    ports:
      - 8088:8080
    depends_on:
      - mic-keygen-postgres
      - mic-redis
    environment:
      - KEYGEN_EDITION=CE
      - KEYGEN_ACCOUNT_ID=filled
      - KEYGEN_HOST=api.keygen.localhost
      - DATABASE_URL=postgres://postgres:postgres@172.18.150.16:5433/postgres
      - REDIS_URL=redis://172.18.150.16:6379
      - SECRET_KEY_BASE=filled
      - ENCRYPTION_DETERMINISTIC_KEY=filled
      - ENCRYPTION_PRIMARY_KEY=filled
      - ENCRYPTION_KEY_DERIVATION_SALT=filled
    extra_hosts:
      - host.docker.internal:host-gateway

  mic-keygen-postgres:
    container_name: keygen-postgres
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mic-redis:
    container_name: keygen-redis
    image: redis:7.2.3-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - ./postgres-data:/var/lib/redis/data
```

Im using my machine IP because it doesn't work with localhost.

I have this error that I don't know how to resolve because I cannot launch keygen container, it crashes on launch. 

```
024-02-29 14:13:18.295 UTC [28] ERROR:  relation "accounts" does not exist at character 491
keygen-postgres  | 2024-02-29 14:13:18.295 UTC [28] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
keygen-postgres  |             pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
keygen-postgres  |             c.collname, col_description(a.attrelid, a.attnum) AS comment,
keygen-postgres  |             attgenerated as attgenerated
keygen-postgres  |        FROM pg_attribute a
keygen-postgres  |        LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
keygen-postgres  |        LEFT JOIN pg_type t ON a.atttypid = t.oid
keygen-postgres  |        LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
keygen-postgres  |       WHERE a.attrelid = '"accounts"'::regclass
keygen-postgres  |         AND a.attnum > 0 AND NOT a.attisdropped
keygen-postgres  |       ORDER BY a.attnum
```

 /usr/local/bundle/ruby/3.2.0/gems/activerecord-7.0.7.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:19:in `exec': PG::UndefinedTable: ERROR:  relation "accounts" does not exist (ActiveRecord::StatementInvalid) LINE 9:  WHERE a.attrelid = '"accounts"'::regclass

With dbeaver I checked 'SELECT * FROM pg_attribute' and 'a.attrelid = '"accounts"' doesn't exist. The table has 3100~ rows but no that one.

Can anyone help me? Thanks in advance.

**Comment by ezekg** [comment]
The error is saying the `accounts` table does not exist. This would indicate that you haven't run [the setup script](https://keygen.sh/docs/self-hosting/#configure-keygen), so the database is empty. The setup step is not optional. Here's a discussion on where we're at i.r.t. docker compose: https://github.com/keygen-sh/keygen-api/issues/727

Please keep in mind that Keygen needs its own database; it cannot be shared with another application.

**Comment by joanesinurrietasmartpm** [comment]
I updated the docker compose file:
```
version: '3.5'

services:
  mic-keygen-postgres:
    container_name: keygen-postgres
    image: postgres:13.14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mic-keygen-redis:
    container_name: keygen-redis
    image: redis:7.2.3-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/var/lib/redis/data
```

Then I created this launch_keygen.sh file which will fill the DB that was empty and was the origin of the problem:

```
#!/bin/bash

SECRET_KEY_BASE="filled"
ENCRYPTION_DETERMINISTIC_KEY="filled"
ENCRYPTION_PRIMARY_KEY="filled"
ENCRYPTION_KEY_DERIVATION_SALT="filled"

DATABASE_URL="postgres://postgres:postgres@host.docker.internal:5433/postgres"
REDIS_URL="redis://host.docker.internal:6379"
KEYGEN_HOST="api.keygen.localhost"
KEYGEN_MODE="singleplayer"
KEYGEN_EDITION="CE"
KEYGEN_ACCOUNT_ID="filled"

DOCKER_IMAGE="keygen/api:v1.2"

docker run --rm -it \
  --network keygen_default \
  -e SECRET_KEY_BASE="$SECRET_KEY_BASE" \
  -e ENCRYPTION_DETERMINISTIC_KEY="$ENCRYPTION_DETERMINISTIC_KEY" \
  -e ENCRYPTION_PRIMARY_KEY="$ENCRYPTION_PRIMARY_KEY" \
  -e ENCRYPTION_KEY_DERIVATION_SALT="$ENCRYPTION_KEY_DERIVATION_SALT" \
  -e DATABASE_URL="$DATABASE_URL" \
  -e REDIS_URL="$REDIS_URL" \
  -e KEYGEN_HOST="$KEYGEN_HOST" \
  -e KEYGEN_MODE="$KEYGEN_MODE" \
  -e KEYGEN_EDITION="$KEYGEN_EDITION" \
  -e KEYGEN_ACCOUNT_ID="$KEYGEN_ACCOUNT_ID" \
  "$DOCKER_IMAGE" setup
```

I was trying to avoid host.docker.internal because in production we have linux environments. I tried using it with windows docker desktop and it worked.

![image](https://github.com/keygen-sh/community/assets/131172312/a3a95fab-d1f1-42ab-b1ce-ee4d9e95c834)

The DB is filled:

![image](https://github.com/keygen-sh/community/assets/131172312/5a04a62e-0718-46c6-a900-fe00f64e04e7)

Finally, I did a 'docker compose down' of the 2 containers (redis and postgres) but if you notice, I am saving the data from the containers on the host volumes in the parameter 'volumes' of both redis and postgres. Then I add the third keygen container and I do docker compose up again, but now with 3 containers and with the db filled.

```
version: '3.5'

services:
  mic-keygen-postgres:
    container_name: keygen-postgres
    image: postgres:13.14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mic-keygen-redis:
    container_name: keygen-redis
    image: redis:7.2.3-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/var/lib/redis/data

  mic-keygen:
    container_name: keygen
    image: keygen/api:v1.2
    ports:
      - 8088:8080
    depends_on:
      - mic-keygen-postgres
      - mic-keygen-redis
    environment:
      - KEYGEN_EDITION=CE
      - KEYGEN_ACCOUNT_ID=filled
      - KEYGEN_HOST=api.keygen.localhost
      - DATABASE_URL=postgres://postgres:postgres@172.18.150.16:5433/postgres
      - REDIS_URL=redis://172.18.150.16:6379
      - SECRET_KEY_BASE=filled
      - ENCRYPTION_DETERMINISTIC_KEY=filled
      - ENCRYPTION_PRIMARY_KEY=filled
      - ENCRYPTION_KEY_DERIVATION_SALT=filled
    extra_hosts:
      - host.docker.internal:host-gateway
```

The result:

![image](https://github.com/keygen-sh/community/assets/131172312/5dea8553-29b1-4a0d-8c63-a82698121b9e)
