### DISCUSSION TITLE
Docker compose setup

### DISCUSSION THREAD

**Discussion by MylesWritesCode** [keygen-sh/community#77] [Q&A] [answered]
Is there anyway to auto-generate a user id without having to run `bundle exec rails keygen:setup`? I'm finding myself needing to change command to `["setup"]` and using exec to set everything up, then changing it back to `["web"]` to actually run the api locally through docker compose. 

```
version: "3.4"
name: keygen-api
services:
  keygen:
    image: keygen/api
    depends_on:
      - postgres
      - redis
    environment:
      KEYGEN_EDITION: ${KEYGEN_EDITION}
      KEYGEN_HOST: ${KEYGEN_HOST}
      KEYGEN_MODE: ${KEYGEN_MODE}
      KEYGEN_ACCOUNT_ID: ${KEYGEN_ACCOUNT_ID}
      ENCRYPTION_PRIMARY_KEY: ${ENCRYPTION_PRIMARY_KEY}
      ENCRYPTION_DETERMINISTIC_KEY: ${ENCRYPTION_DETERMINISTIC_KEY}
      ENCRYPTION_KEY_DERIVATION_SALT: ${ENCRYPTION_KEY_DERIVATION_SALT}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: ${KEYGEN_PORT}
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
    command: ["web"]
    stdin_open: true
    tty: true
  postgres:
    image: postgres:alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: redis:alpine
    ports:
      - ${RDPORT}:6379
    volumes:
      - ./.data/redis:/data
    deploy:
      resources:
        limits:
          memory: 64M
```
